change in compose file

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -7,35 +7,38 @@ on:
 
 jobs:
   build-test-deploy:
-    runs-on: ubuntu-letest
+    runs-on: ubuntu-latest
 
     steps:
-      - name: checking codes
-        uses : action/setup-python@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Setup Python
+        uses: actions/setup-python@v4
         with:
           python-version: "3.10"
 
-      - name:
+      - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install -r requir.txt
+          pip install -r requirements.txt
 
-      - name: building docker image
+      - name: Build Docker image
         run: |
-          docker compose up --build -d
+          docker build -t rag_app:latest .
 
-      - name: checking secrets are present
+      - name: Check required secrets
         run: |
-          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "DOCKER_USERNAME is missing"; fi
-          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then echo "DOCKER_PASSWORD is missing"; fi
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "Missing DOCKER_USERNAME" && exit 1; fi
+          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then echo "Missing DOCKERHUB_TOKEN " && exit 1; fi
 
-      - name: login to docker Hub
+      - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
-          username: ${{secrets.DOCKER_USERNAME}}
-          password: ${{secrets.DOCKER_PASSWORD}}
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name : push docker image
+      - name: Tag & Push Image
         run: |
-          docker tag RAGapp:latest ${{ secrets.DOCKER_USERNAME }}/RAGapp:latest
-          docker push ${{ secrets.DOCKER_USERNAME }}/RAGapp:latest
+          docker tag rag_app:latest ${{ secrets.DOCKER_USERNAME }}/rag_app:latest
+          docker push ${{ secrets.DOCKER_USERNAME }}/rag_app:latest
